# Generated by Django 3.1 on 2020-09-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='lastUpdated',
        ),
    ]
