# Generated by Django 3.1 on 2020-09-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_item_lastupdated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='seen',
        ),
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='linkText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
